version: '3.4'

services:
  moviesmanagementdb:
    container_name: moviesmanagementdb
    environment:
      SA_PASSWORD: "Bob12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  moviesmanagement.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:MoviesManagementWebAppContext=Server=moviesmanagementdb;Database=MoviesManagementWebAppContext-0c872193-1c86-4864-a806-485ab7d3952f;User Id=sa;Password=Bob12345678"
    depends_on:
      - moviesmanagementdb
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data